export const DUMMY_DATA = [
  {
    volanta: "Volanta",
    titulo: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    bajada: "Lana soñaba con volar a la luna. Todas las tardes se tumbaba",
    img: "",
    marquesina: "Marquesina 1",
    autor: "full name",
    autImg: "",
    url: "www.url.com",
  },
  {
    volanta: "Volanta",
    titulo: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    bajada: "Lana soñaba con volar a la luna. Todas las tardes se tumbaba",
    img: "",
    marquesina: "Marquesina 1",
    autor: "full name",
    autImg: "",
    url: "www.url.com",
  },
  {
    volanta: "Volanta",
    titulo: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    bajada: "Lana soñaba con volar a la luna. Todas las tardes se tumbaba",
    img: "",
    marquesina: "Marquesina 1",
    autor: "full name",
    autImg: "",
    url: "www.url.com",
  },
  {
    volanta: "Volanta",
    titulo: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    bajada: "Lana soñaba con volar a la luna. Todas las tardes se tumbaba",
    img: "",
    marquesina: "Marquesina 1",
    autor: "full name",
    autImg: "",
    url: "www.url.com",
  },
  {
    volanta: "Volanta",
    titulo: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    bajada: "Lana soñaba con volar a la luna. Todas las tardes se tumbaba",
    img: "",
    marquesina: "Marquesina 1",
    autor: "full name",
    autImg: "",
    url: "www.url.com",
  },
];
